names_to_emails = {'22minnes@cpsd.us' : 'MAX INNES',
                   '19abaptista@cpsd.us' : 'ALEXANDER BAPTISTA',
                   '22rberman@cpsd.us' : 'RALEIGH BERMAN',
                   '19ssheikh@cpsd.us' : 'SAHIL SHEIKH',
                   '21nserfaty@cpsd.us' : 'NATASHA SERFATY',
                   '19osaffery@cpsd.us' : 'OLIVER SAFFERY',
                   '19acolas@cpsd.us' : 'ANDRE COLAS',
                   '20egichile@cpsd.us' : 'Emmanuel Gichile',
                   '19mmelaku@cpsd.us' : 'MICHAEL MELAKU',
                   '19rkabir@cpsd.us' : 'Rakib Kabir',
                   '21fsaunders-zurn@cpsd.us' : 'FINN SAUNDERS-ZURN',
                   '20msater@cpsd.us' : 'Maya Sater',
                   '20hlin@cpsd.us' : 'HORACE LIN',
                   '21mislam@cpsd.us' : 'MOHAMMED ISLAM', 
                   '22akillian@cpsd.us' : 'Anais Killian',
                   '20dgebretensae@cpsd.us' : 'DINA GEBRETENSAE',
                   '22rblumofe@cpsd.us' : 'Ryan Blumofe',
                   '20gkatz@cpsd.us' : 'GIDEON KATZ',
                   '19cdavis@cpsd.us' : 'Cai Davis',
                   '19fduverglas@cpsd.us' : 'FRITZ-GERALD DUVERGLAS',
                   '19hmacarthur@cpsd.us' : 'HAROLD MACARTHUR',
                   '19aharp@cpsd.us' : 'ANYA HARP',
                   '19ebeaumontsmith@cpsd.us' : 'EMMA BEAUMONT-SMITH',
                   '21akanade@cpsd.us' : 'Anish Kanade',
                   '21pmurphy@cpsd.us' : 'Peter Murphy',
                   '21hklapper@cpsd.us': 'HAROLD KLAPPER',
                   '22kpingle@cpsd.us' : 'KARTIK PINGLE',
                   '21lmuhameid@cpsd.us' : 'LAMIYA MUHAMEID',
                   '20acunningham@cpsd.us' : 'ANYA CUNNINGHAM',
                   '21sfakir@cpsd.us' : 'Shahnawaz Fakir',
                   '21fabdullah@cpsd.us' : 'FARAH ABDULLAH',
}
